packages:
  - packages/worker
  - packages/dsl
  - packages/extension

allowBuilds:
  esbuild: true
  msw: true
  sharp: true
  spawn-sync: true
  unrs-resolver: true
  vue-demi: true
  workerd: true

lockfileIncludeTarballUrl: true
minimumReleaseAgeExclude:
  # See https://github.com/sxzz/rolldown-plugin-dts/issues/277#issuecomment-5009624632
  - yuku-parser@0.6.9
  - "@yuku-parser/binding-darwin-arm64@0.6.9"
  - "@yuku-parser/binding-darwin-x64@0.6.9"
  - "@yuku-parser/binding-freebsd-x64@0.6.9"
  - "@yuku-parser/binding-linux-arm-gnu@0.6.9"
  - "@yuku-parser/binding-linux-arm-musl@0.6.9"
  - "@yuku-parser/binding-linux-arm64-gnu@0.6.9"
  - "@yuku-parser/binding-linux-arm64-musl@0.6.9"
  - "@yuku-parser/binding-linux-x64-gnu@0.6.9"
  - "@yuku-parser/binding-linux-x64-musl@0.6.9"
  - "@yuku-parser/binding-win32-arm64@0.6.9"
  - "@yuku-parser/binding-win32-x64@0.6.9"

catalog:
  typescript: ^6.0.3
  vitest: ^4.1.10

patchedDependencies:
  "@truto/sqlite-builder@1.0.4": patches/@truto__sqlite-builder@1.0.4.patch
