packages:
  - packages/worker
  - packages/dsl
  - packages/extension

allowBuilds:
  esbuild: true
  sharp: true
  spawn-sync: true
  unrs-resolver: true
  vue-demi: true
  workerd: true

lockfileIncludeTarballUrl: true

patchedDependencies:
  "@truto/sqlite-builder@1.0.4": patches/@truto__sqlite-builder@1.0.4.patch
